ellie-commons/taxi

data/icons/128/taxi.svg
data/icons/24/taxi.svg
data/icons/32/taxi.svg
data/icons/48/taxi.svg
data/icons/64/taxi.svg

Use the latest elementary palette

Update Icon palette

---

data/com.github.Alecaddd.taxi.desktop.in

We don't want this old stuff in here :p

Remove About dialog action

---

data/Application.css
data/css.gresource.xml
meson.build
src/Frontend/GUI.vala

* Move custom CSS to an external file and load with GResource
* Update selectors to work with Gtk 3.22
* Assume elementary stylesheet and drop a bunch of other crap

Fix CSS for Gtk 3.22

---

src/Frontend/GUI.vala
src/Taxi.vala

There's a lot of crazy stuff happening here but this branch:
* Uses GObject style
* Moves a lot of single-use methods into the `construct` block
* Reduces variable scope where possible

GUI.vala: Rewrite in GObject style

---

src/Frontend/Widgets/ConnectBox.vala

* GObject style construct
* Simplify some single use methods
* Subclass grid instead of box
* Explicitly scope variables

ConnectBox.vala: GObject style and cleanup

---

src/Frontend/Widgets/FilePane.vala

FilePane: Style empty folder label the same as Files

---

src/Frontend/GUI.vala
src/Frontend/Widgets/ConnectBox.vala

Move bookmarks to the right of the URL bar and make the icon colored to match Epiphany

GUI: Move bookmarks to match Epiphany

---

src/Frontend/Widgets/PathBar.vala

Ellipsize labels for long paths and add tooltips

PathBar: ellipsize labels and add tooltips

---

src/Frontend/GUI.vala

Send a nice little toast instead of a big red infobar for feedback

GUI: Use Granite.Toast instead of Infobar

---

src/Frontend/GUI.vala
src/Frontend/Widgets/ConnectBox.vala

Make the bookmarks menu function

---

src/Frontend/Widgets/FilePane.vala

FilePane: Fix spinner size

---

src/Frontend/Widgets/FilePane.vala

* Use a Gtk.Stack to show the spinner instead of messing with widget visibility
* Get rid of some single use methods
* Reduce variable scope where possible
* Organize

FilePane: Use Gtk.Stack and misc Cleanup

---

src/Frontend/Widgets/FilePane.vala

* Get rid of single use methods
* Remove unnecessary aligns
* Use Gtk.Grid instead of Box for simple column spacing

FilePane: Simply new row method

---

src/API/IFileAccess.vala
src/API/IFileOperations.vala
src/Backend/FileAccess.vala
src/Backend/FileOperations.vala

Solve a couple Terminal warnings by removing unused methods

Remove unused methods

---

muckups/bookmarks.svg
muckups/main.svg

UI mockups for future references

---

src/Application.vala
src/meson.build

Application: Respect dark style preference

---

.github/workflows/ci.yml
com.github.alecaddd.taxi.yml

Add Flatpak manifest

---

data/com.github.alecaddd.taxi.appdata.xml.in

AppData: Add stripe key

---

data/com.github.alecaddd.taxi.gschema.xml
src/Frontend/MainWindow.vala

Handled by the window manager these days, can't position ourselves in Wayland

Remove window positioning

---

src/Frontend/Widgets/PathBar.vala

Pathbar: fix invalid uri on button clicked
